### ISSUE TITLE
Game Crashed on attempting to spawn my first clay soldier (Red)

### ISSUE THREAD

**Issue by GeekyBakerBen** [matthewperiut/Clay-Soldiers#4]
Have had this mod in the background on my multiplayer hosted server for a while, but just tried to actually spawn my first clay soldier.

Crafted 4 soldiers, re-dyed them Red, Blue, Yellow, Lime Green. As soon as I tried to place the first clay soldier (Red) on the floor, the game crashed with the following:

> The game crashed whilst rendering entity in world
Error: java.lang.AbstractMethodError: Receiver class com.matthewperiut.clay.entity.soldier.variant.RedSoldierDoll does not define or inherit an implementation of the resolved method 'abstract void registerControllers(software.bernie.geckolib.core.animation.AnimatableManager)' of interface software.bernie.geckolib.core.animatable.GeoAnimatable.

The error on my server log
> Server thread/WARN Lithium Class Analysis Error: Class com.matthewperiut.clay.entity.soldier.SoldierDollEntity cannot be analysed, because getting declared methods crashes with NoClassDefFoundError: software/bernie/geckolib/core/animation/AnimationState. This is usually caused by modded entities declaring methods that have a return type or parameter type that is annotated with @Environment(value=EnvType.CLIENT). Loading the type is not possible, because it only exists in the CLIENT environment. The recommended fix is to annotate the method with this argument or return type with the same annotation. Lithium handles this error by assuming the class cannot be included in some optimizations.

**Version of Mod: Fabric 0.4.3 for 1.19.3
Version of geckolib: 1.19.3 - 3.1.38 and also rc2 4.0.0**

**Full Crash Report:**

> ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-02-21 21:02:46
Description: Rendering entity in world

java.lang.AbstractMethodError: Receiver class com.matthewperiut.clay.entity.soldier.variant.RedSoldierDoll does not define or inherit an implementation of the resolved method 'abstract void registerControllers(software.bernie.geckolib.core.animation.AnimatableManager)' of interface software.bernie.geckolib.core.animatable.GeoAnimatable.
	at software.bernie.geckolib.core.animatable.instance.InstancedAnimatableInstanceCache.getManagerForId(InstancedAnimatableInstanceCache.java:26)
	at software.bernie.geckolib.model.GeoModel.handleAnimations(GeoModel.java:134)
	at software.bernie.geckolib.renderer.GeoEntityRenderer.actuallyRender(GeoEntityRenderer.java:226)
	at software.bernie.geckolib.renderer.GeoEntityRenderer.actuallyRender(GeoEntityRenderer.java:47)
	at software.bernie.geckolib.renderer.GeoRenderer.defaultRender(GeoRenderer.java:130)
	at software.bernie.geckolib.renderer.GeoEntityRenderer.method_3936(GeoEntityRenderer.java:151)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:593)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:472)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$cel000$iris$renderTerrainShadows(class_761.java:9768)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$bpm000$redirectRenderingWorld(class_757.java:3706)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
=======

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib.core.animatable.instance.InstancedAnimatableInstanceCache.getManagerForId(InstancedAnimatableInstanceCache.java:26)
	at software.bernie.geckolib.model.GeoModel.handleAnimations(GeoModel.java:134)
	at software.bernie.geckolib.renderer.GeoEntityRenderer.actuallyRender(GeoEntityRenderer.java:226)
	at software.bernie.geckolib.renderer.GeoEntityRenderer.actuallyRender(GeoEntityRenderer.java:47)
	at software.bernie.geckolib.renderer.GeoRenderer.defaultRender(GeoRenderer.java:130)
	at software.bernie.geckolib.renderer.GeoEntityRenderer.method_3936(GeoEntityRenderer.java:151)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:593)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:472)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$cel000$iris$renderTerrainShadows(class_761.java:9768)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$bpm000$redirectRenderingWorld(class_757.java:3706)

-- Entity being rendered --
Details:
	Entity Type: clay:soldier/red (com.matthewperiut.clay.entity.soldier.variant.RedSoldierDoll)
	Entity ID: 13614
	Entity Name: Red Soldier
	Entity's Exact location: -464.50, 68.00, -410.50
	Entity's Block location: World: (-465,68,-411), Section: (at 15,4,5 in -30,4,-26; chunk contains blocks -480,-64,-416 to -465,319,-401), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:593)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:472)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$cel000$iris$renderTerrainShadows(class_761.java:9768)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$bpm000$redirectRenderingWorld(class_757.java:3706)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: com.matthewperiut.clay.entity.client.SoldierDollRenderer@e67f1e4
	Location: 1.49,-1.62,-1.34 - World: (1,-2,-2), Section: (at 1,14,14 in 0,-1,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: -167.34375
	Delta: 0.32028055
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:593)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:472)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$cel000$iris$renderTerrainShadows(class_761.java:9768)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$bpm000$redirectRenderingWorld(class_757.java:3706)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['GeekyPup'/3, l='ClientWorld minecraft:overworld', x=-465.99, y=68.00, z=-409.16]]
	Chunk stats: Client Chunks (ImmPtl) 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,128,0), Section: (at 0,0,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 29374360 game time, 30304861 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, cullleaves/smartleaves, file/Better-Leaves-7.1-1.19+.zip, minecraft/supporteatinganimation, file/TissousZombie-Resource-Pack-16x-1.19.zip, file/xali's+Potions+v1.0.zip, file/xali's+Potions_EMISSIVE+v.1.0.zip, file/BrewingCanvas_v0.6_1.19.zip, file/3d-lanterns-chains.zip, file/§bGoldenGlint§8-[v1.1].zip

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 623024728 bytes (594 MiB) / 2013265920 bytes (1920 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f07
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Graphics card #1 name: Intel(R) HD Graphics 4600
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x0412
	Graphics card #1 versionInfo: DriverVersion=20.19.15.4835
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 20703.69
	Virtual memory used (MB): 17481.41
	Swap memory total (MB): 4432.68
	Swap memory used (MB): 471.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.3-fabric0.68.1-1.3.1
		ambientsounds: Ambient Sounds (Fabric) 5.2.17
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19.3
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.2+mc1.19.3
		aqupdgrizzly: Grizzly Bear mob 1.19.3-1.4
		architectury: Architectury 7.0.66
		autoconfig1u: Auto Config v1 Updated 3.4.0
		badpackets: Bad Packets 0.3.4
		balm-fabric: Balm 5.0.2
		bedrockify: BedrockIfy 1.5.4+mc1.19.3
		betterthanllamas: Better Than Llamas 1.2.0
		bobby: Bobby 4.0.3
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bottleyourxp: Bottle Your Xp 3.0
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		cenchants: Combat Enchants 2.14.5
		charmofreturn: Charm of Return 1.0.1
			net_objecthunter_exp4j: exp4j 0.4.8
		citresewn: CIT Resewn 1.1.3+1.19.3
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.3
		clay: Clay Soldiers 0.4.3
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.43
		comforts: Comforts 6.1.1+1.19.3
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			spectrelib: SpectreLib 0.12.1+1.19.2
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		companion_bats: Companion Bats 1.19.2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		creativecore: CreativeCore (Fabric) 2.10.4
			net_minecraftforge_eventbus: eventbus 6.0.4
		creeper_firework: Creeper Firework 1.5.0
		ctov: ChoiceTheorem's Overhauled Villages 3.1.4
		cull-less-leaves: Cull Less Leaves 1.1.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
		cullleaves: Cull Leaves 3.0.2
			midnightlib: MidnightLib 1.1.0
		dawn: Dawn API 4.0.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 5.0.0-beta.1
			terraform-wood-api-v1: Terraform Wood API (v1) 5.0.0-beta.1
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19.3
		eatinganimationid: Eating Animation 1.9.1
		entity_texture_features: Entity Texture Features 4.3.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.73.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.11+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.0+06937c4b85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.43+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.9+c3530bb185
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.30+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.28+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.0+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.0+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+eb2a3ba985
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		fallingleaves: Falling Leaves 1.14.4+1.19.3
		fennecfox: Fennec Fox 1.0.0
		ferritecore: FerriteCore 5.1.0
		flesh2leather: Flesh2Leather 1.0.4+1.19.3
		flowerpatch: Flower Patch 1.2.0
		geckolib: Geckolib 4.0.0
			com_eliotlash_mclib_mclib: mclib 20
		geckolib3: Geckolib 3.1.38
		gimme_bundles: Gimme bundles! 1.0.6
		gravestones: Gravestones v1.14
		handcrafted: Handcrafted 2.0.4
		immersive_portals: Immersive Portals 2.4.8
			imm_ptl_core: Immersive Portals Core 2.4.8
			q_misc_util: QMiscUtil 2.4.8
		indium: Indium 1.0.12+mc1.19.3
		inventorytotem: Inventory Totem 3.0
		invisframes: Invisible Frames 2.2.0
		iris: Iris 1.5.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		lambdynlights: LambDynamicLights 2.2.0+1.19.3
			pride: Pride Lib 1.2.0+1.19.3
			spruceui: SpruceUI 4.1.0+1.19.3
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.10.4
		mcwbridges: Macaw's Bridges 2.0.6
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwtrpdoors: Macaw's Trapdoors 1.0.8
		mcwwindows: Macaw's Windows 2.1.2
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		minecraft: Minecraft 1.19.3
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mo_glass: Mo Glass 1.6.1-MC1.19.3-rc3
		modmenu: Mod Menu 5.0.2
		no_more_purple: No More Purple 1.0.1
		notenoughanimations: NotEnoughAnimations 1.6.2
		npcvariety: NPC Variety 2.3.0
		patchouli: Patchouli 1.19.3-78-FABRIC
			fiber: fiber 0.23.0-2
		phosphor: Phosphor 0.8.1
		physicsmod: Physics Mod 2.10.1
		presencefootsteps: Presence Footsteps 1.7.1
			kirin: Kirin UI 1.13.2
		promenade: Promenade 3.0.0
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		resourcefullib: Resourceful Lib 1.2.7
			com_teamresourceful_yabn: yabn 1.0.2
		roughlyenoughitems: Roughly Enough Items 10.0.586
			error_notifier: Error Notifier 1.0.9
		showmeyourskin: Show Me Your Skin! 1.3.7+1.19.3
			cicada: CICADA 0.1.1
				langfiles-plus: Langfiles Plus 1.0.0
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.3
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.4.8+build.22
		sodium-extra: Sodium Extra 0.4.16+mc1.19.3-build.91
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		terrablender: TerraBlender 2.1.0.139
		villagerdeathmessages: Villager Death Messages 3.1
		villagers-follow-emeralds: Villagers Follow Emeralds 1.3.0
		visuality: Visuality 0.6.0
		vulture: Vulture Mod 1.0.1
		walllanterns: Lanterns Belong on Walls 1.4.1-1.19.3
		weaponmaster: YDM's Weapon Master 3.0.5
		xercapaint: Joy of Painting fabric-1.19.3-1.0.0
		ydms_redpanda: YDM's Red Panda 1.0.4
		yet-another-config-lib: YetAnotherConfigLib 2.2.0
		zombify: Fampat Zombify Mod 0.9.1
	Loaded Shaderpack: ComplementaryShaders_v4.7.zip
		Profile: Custom (+11 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.14-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.49, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, cullleaves:smartleaves, file/Better-Leaves-7.1-1.19+.zip (incompatible), minecraft:supporteatinganimation, file/TissousZombie-Resource-Pack-16x-1.19.zip (incompatible), file/xali's+Potions+v1.0.zip (incompatible), file/xali's+Potions_EMISSIVE+v.1.0.zip (incompatible), file/BrewingCanvas_v0.6_1.19.zip (incompatible), file/3d-lanterns-chains.zip, file/§bGoldenGlint§8-[v1.1].zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz

**Comment by matthewperiut** [comment]
Cannot replicate, most likely Geckolib version issue, attempted to reproduce on
Forge Server + Forge Client
Fabric Server + Fabric Client
Mods:
Geckolib 4.2.1
Minecraft 1.20.1
Clay 0.5.0
